import cerbose
from cerbose import cprint, mprint

cprint("none", "I like frogs.")
cprint("ok", "I like frogs.")
cprint("note", "I like frogs.")
cprint("warn", "I like frogs.")
cprint("error", "I like frogs.")
cprint("debug", "I like frogs.")
cprint("info", "I like frogs.")
cprint("input", "I like frogs.")
cprint("load", "I like frogs.")
cprint("pause", "I like frogs.")
cprint("stat", f"{cerbose.cerbar(20, 70, 42)} I like frogs.")
cprint("fatal", "I like frogs.")
cprint("trace", "I like frogs.")
cprint("proc", "I like frogs.")
cprint("rege", "Repeat explained in README/docs. I still like frogs.")
cprint("", "I like frogs.")
cprint("info", "Double tag test. I still like frogs.", stagtype="debug")
cprint("debug", "Text colour test. I still like frogs.", textcol="yellow")
cprint("debug", "Timestamp test. I still like frogs.", timestamp=True)
cerbose.resetalign()
mprint("warn", "Multi-line test.\nI still like frogs.")
inp = cerbose.cin('t', 'info', 'Give feedback on the frogs.', 'any', stagtype='warn')
cprint("info", f"You typed {inp}!")